### ISSUE TITLE
基于Snowflake的Hash-Sharding分片算法

### ISSUE THREAD

**Issue by xydonne** [shardingjdbc/sharding-jdbc#186]
# 特性：
* 在主键为Snowflake算法生成ID时可使用。
* 极大简化分库分表配置
* 拓展库表不需要做数据迁移

# 原理：
根据SnowflakeID生成三个维度的值
timestamp：SnowflakeID的前42位
根据此值可以指定一个时间点，对此时间点后的库表关系进行重映射，在不做数据迁移的情况下拓展库表
databaseHash：SnowflakeID通过MurmurHash算法生成32位Hash值的前16位
最大可分65536个库（0x0000 - 0xFFFF）
tableHash：SnowflakeID通过MurmurHash算法生成32位Hash值的后16位
最大可分65536个表（0x0000 - 0xFFFF）

# yaml配置
```yaml
dataSource:
  db0: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  db1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  db2: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  db3: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

hash:
  snowflake_hash.id:
    2016-10-31T17:00:00:
      0x0000:
        database: db0
        tables:
          0x0000: t_snowflake_hash_0
          0x8000: t_snowflake_hash_1
      0x8000:
        database: db1
        tables:
          0x0000: t_snowflake_hash_2
          0x8000: t_snowflake_hash_3
    2016-11-20T17:00:00+08:
      0x0000:
        database: db2
        tables:
          0x0000: t_snowflake_hash_4
          0x8000: t_snowflake_hash_5
      0x8000:
        database: db3
        tables:
          0x0000: t_snowflake_hash_6
          0x8000: t_snowflake_hash_7
```

在此种规则下，原本的BetweenSharding没有太大意义。
所以改成新的查询方式BETWEEN #{lower} AND #{upper}
lower：
前32位（(lowerTimestamp >>> 10)-1<<32 ）
中16位（lowerDatabaseHash）
后16位（lowerTableHash）
upper：
前32位（(upperTimestamp >>> 10)+1<<32 ）
中16位（upperDatabaseHash）
后16位（upperTableHash）
表示查询lowerTimestamp到upperTimestamp时间段内，lowerDatabaseHash到upperDatabaseHash数据库分片，lowerTableHash到upperTableHash表分片的数据。

# TODO：
1. 配置的参数校验
2. 目前走的是dynamic=true的方式，将会有一堆问题。

# dynamic=true导致的问题：
1. 无法写H2的单元测试，因为实际的语句是SELECT * FROM db.table，H2会把db字段当成schema，导致无法查询。
2. dynamic=true情况下因为没有映射关系，所以无分片键值的情况下无法做全映射，但Hash-Sharding有全映射关系，本质上可以在无分片键值的情况下做全映射。
3. HashDatabaseAlgorithm这个类是多余的，HashAlgorithm足够维护全部的映射关系。
4. 以SELECT * FROM db.table的方式对所有的库进行了查询，实际上可以通过db.table查询指定的库，而非全查。
5. 因为以SELECT * FROM db.table方式查询，所以dsName得和真实dbName一致，不然会出错。

# DEMO：
https://github.com/xydonne/sharding-jdbc/tree/hash-sharding/186
参见hash-sharding/186分支，把测试用例当DEMO写了。

**Comment by hanahmily** [comment]
目前你的这个想法是做了两层映射，第一层其实是一个线性递增，第二层是一个hash均匀。这样达到两个目的，可以横向扩展有能保证数据分布均匀。思想与这篇文章比较接近[一种支持自由规划无须数据迁移和修改路由代码的Sharding扩容方案](http://blog.csdn.net/bluishglc/article/details/7970268)。

关于算法有一个问题：
1. hash部分，为什么要对高位和低位分别对应分库和分表？可以拿同一个hash值去映射嘛？

关于yaml配置有几个问题：
1. 如果配置的时候用16进制，那么就太不明确了。可以考虑redis cluster的做法，用十进制数去配置。而且要配置范围，而不是只配置分割数。
1. 不要用数值当做key。且数据要明确

举例来说，如下配置：
```yaml
2016-10-31T17:00:00:
      0x0000:
        database: db0
        tables:
          0x0000: t_snowflake_hash_0
          0x8000: t_snowflake_hash_1
```
应该配置为：
```yaml
timeRange: less than 2016-10-31T17:00:00
databases:
    - databaseRange: less than 0x8000
       database: db0
       tables:
           - tableRange: less than  0x8000
              tableName: t_snowflake_hash_0
           - tableRange: less than MAXVALUE
              tableName: t_snowflake_hash_1
```

关于动态表的问题，由于你实现的只是一个算法。其实不用考虑使用你这个算法的人是否使用动态表或不是动态的表。

最后demo我看了一下 ，Guava实现了[murmur3_32 算法](https://google.github.io/guava/releases/17.0/api/docs/com/google/common/hash/Hashing.html)，这就不要自己去实现了
