### ISSUE TITLE
README的yaml配置不支持2.0

### ISSUE THREAD

**Issue by wendal** [shardingjdbc/sharding-jdbc#481]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0
### Expected behavior
正常启动
### Actual behavior
报tables属性不存在
### Steps to reproduce the behavior
把README提供的yaml文件存为demo.yaml,然后启动
### Please provide the reproduce example codes (such as github link) if possible.

```yaml
shardingRule: // <--- 2.0多了这一层, 1.x没有这一层
  tables:
    t_order: 
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      databaseStrategy: 
        inline:
          shardingColumn: user_id
          algorithmExpression: ds_${user_id % 2}
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
```
